version: '3'
services:
  opensearch-node1:
    # build the image following https://github.com/gsingers/opensearch-learning-to-rank/blob/main/README.md
    image: vitalii/opensearch-learning-to-rank
    container_name: opensearch-node1
    environment:
      - discovery.type=single-node
      - http.max_content_length=2000mb
      - "OPENSEARCH_JAVA_OPTS=-Xms4G -Xmx8G" # Start with 4Gb of memory, and allow to use up to 8G of memory.

    volumes:
      - opensearch-data1:/usr/share/opensearch/data  #todo: figure this out so we can have persistent storage
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - opensearch-net
  
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:1.2.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200"]'
    depends_on:
      - opensearch-node1
    networks:
      - opensearch-net

volumes:
  opensearch-data1:

networks:
  opensearch-net:
    driver: bridge
